name: simplify_dart
description: A dart port of the Simplify.js polyline simplification library by Vladimir Agafonkin
version: 1.3.0
homepage: https://github.com/moovida/simplify_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
